### ISSUE TITLE
not work!

### ISSUE THREAD

**Issue by xerron** [steckerhalter/ob-php#1]
Ubuntu 16.04
PHP 7

```org-mode
#+BEGIN_SRC php
$test = array(
    array('forest', 'green'),
    array('sea',  $sea),
);

foreach ($test as $row) {
    foreach($row as $cell) { print '|' . $cell; };
    print "\n";
}
#+END_SRC

#+RESULTS:
: $test = array(
:     array('forest', 'green'),
:     array('sea',  $sea),
: );
: 
: foreach ($test as $row) {
:     foreach($row as $cell) { print '|' . $cell; };
:     print "\n";
: }
```

I install boris. 
and install php-boris in emacs.

run boris in terminal -> OK (boris is in $PATH)
php-boris run in emacs-> OK.

but. C-c C-c generate string code.

**Comment by steckerhalter** [comment]
I haven't really used this for years. I tested it now and it seems to work ok (which really kind of surprises me :)

```
#+BEGIN_SRC php :var sea="blue" :results output org
  $test = array(
      array('snow', 'white'),
      array('sea',  $sea),
  );

  foreach ($test as $row) {
      foreach($row as $cell) { print '|' . $cell; };
      print "\n";
  }
#+END_SRC

#+RESULTS:
#+BEGIN_SRC org
| snow | white |
| sea  | blue  |
#+END_SRC
```

In your example you haven't defined the variable `$sea` in the header so it cannot work since the variable is used in the block. And also if you don't specifiy `:results output org` it will print the return value which is nothing in this case.

**Comment by xerron** [comment]
I confused myself as a repository. sorry. with stardiviner/ob-php
I have not tried it, but I think yours should work. But should update it with PsySH.
Thanks for answering.

**Comment by steckerhalter** [comment]
No problem and you're welcome.
